/**
 * @description       : 
 * @author            : Sangram Keshari Upadhyaya
 * @group             : 
 * @last modified on  : 15-09-2025
 * @last modified by  : Sangram Keshari Upadhyaya 
 * Modifications Log
 * Ver   Date         Author                      Modification
 * 1.0   15-09-2025   Sangram Keshari Upadhyaya   Initial Version
**/
public class Manager extends Employee {
    
    public static void handleTeam(){
        
    }
    
    public static void ensureDeliverability(){
        
    }
    
    public static void handleEscalations(){
        
    }
    
    public static void handleAppraisals(){
        
    }
    
    public override void deliverQuality(Integer storiesCompleted, Integer hoursInOffice){
        System.debug('The manager is also good.');
    }

}