/**
 * @description       : 
 * @author            : Sangram Keshari Upadhyaya
 * @group             : 
 * @last modified on  : 15-09-2025
 * @last modified by  : Sangram Keshari Upadhyaya 
 * Modifications Log
 * Ver   Date         Author                      Modification
 * 1.0   15-09-2025   Sangram Keshari Upadhyaya   Initial Version
**/
public class Variables {

    public Integer i = 45;
    private Boolean checkIfRecordExists = true;
    Date d;
    DateTime dt;
    String s = 'Sangram';
    Account accRec = null;
    Contact conRec;
    Set<Id> setId;
    List<Account> accList;
    
}